# Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

application: google.com:tavern-debug
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /(.*\.ico)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.ico)

- url: /img/
  static_dir: static/img

- url: /.*
  script: pub_dartlang.app

libraries:
- name: pycrypto
  version: "2.6"

inbound_services:
- warmup
